version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/raymoo42/lulbot
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build lulbot.go
      - store_artifacts:
          path: lulbot
          prefix: bin
      - add_ssh_keys:
          fingerprints:
            - "01:ca:bb:b7:36:52:4a:86:d0:01:b1:d3:04:05:ce:a9"
      - run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null lulbot stu@www.just-monika.de:~/
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null stu@www.just-monika.de sudo docker build -t lulbot .
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null stu@www.just-monika.de sudo docker-compose -f /opt/app/docker-compose.yml down
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null stu@www.just-monika.de sudo docker-compose -f /opt/app/docker-compose.yml up -d

